---
name: Uptime Kuma Full Access
version: dev
slug: uptime-kuma
description: It is a self-hosted monitoring tool like "Uptime Robot"
url: https://github.com/Zajsoft/addon-uptime-kuma_fa
host_network: true
webui: http://[HOST]:[PORT:3001]
init: false
arch:
  - aarch64
  - amd64
ports:
  3001/tcp: 3001
ports_description:
  3001/tcp: Web interface
discovery:
  - uptime_kuma
